version: 2.1

orbs:
  win: circleci/windows@4.1.1
  
jobs:
  build:
    executor: win/server-2022
    
    steps:
      - checkout
      - run:
          name: echo
          command: echo "Hello, world"
